from pathlib import Path

SEED = 42
FAKER_LOCALE = "en_US"

BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "output"

SOURCE_SYSTEM = "banking_oltp"

NUM_BRANCHES = 10
NUM_CUSTOMERS = 300
NUM_ACCOUNTS = 700
NUM_VALID_TRANSACTIONS = 5000
JOINT_ACCOUNT_RATIO = 0.12
BALANCE_SNAPSHOTS_PER_ACCOUNT = 4
NUM_LOANS = 150

DATE_RANGE_START = "2023-01-01"
DATE_RANGE_END = "2025-12-31"

TRANSACTION_DATE_START = "2025-01-01"
TRANSACTION_DATE_END = "2025-12-31"

ALLOWED_CURRENCIES = ["AZN", "USD", "EUR"]
ACCOUNT_TYPES = ["CHECKING", "SAVINGS", "BUSINESS", "LOAN"]
ACCOUNT_TYPE_WEIGHTS = [0.40, 0.35, 0.10, 0.15]
ACCOUNT_STATUSES = ["ACTIVE", "DORMANT", "CLOSED"]
ACCOUNT_STATUS_WEIGHTS = [0.80, 0.12, 0.08]
TRANSACTION_TYPES = ["DEPOSIT", "WITHDRAWAL", "TRANSFER", "PAYMENT", "FEE"]
TRANSACTION_CHANNELS = ["BRANCH", "ATM", "ONLINE", "MOBILE"]
CUSTOMER_SEGMENTS = ["RETAIL", "PREMIUM", "PRIVATE"]
CUSTOMER_SEGMENT_WEIGHTS = [0.70, 0.22, 0.08]
LOAN_STATUSES = ["APPLIED", "APPROVED", "DISBURSED", "CLOSED", "REJECTED"]
LOAN_STATUS_WEIGHTS = [0.10, 0.10, 0.35, 0.35, 0.10]

DUPLICATE_TRANSACTION_ID = 4
NULL_AMOUNT_TRANSACTION_ID = 6
ORPHAN_TRANSACTION_ID = 7
ORPHAN_ACCOUNT_ID = 999
INVALID_AMOUNT_CURRENCY_TRANSACTION_ID = 8
INVALID_AMOUNT_VALUE = -50
INVALID_CURRENCY_VALUE = "XXX"

CSV_ENCODING = "utf-8"
CSV_NULL_REPRESENTATION = ""
DATE_FORMAT = "%Y-%m-%d"
TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%SZ"